#ifndef _ERRTYPE_H_
#define _ERRTYPE_H_

#define UNDEFINED_VAR 0
#define UNDEFINED_FIELD 1
#define UNDEFINED_STRUCT 2
#define UNDEFINED_FUNC 3

#define REDEFINED_VAR 4
#define REDEFINED_FIELD 5
#define REDEFINED_STRUCT 6
#define REDEFINED_FUNC 7

#define CONFLIT_FUNC 8

#define MISMATCHED_ASSIGNMENT 9
#define MISMATCHED_OPERAND 10
#define MISMATCHED_RETURN 11
#define ERR_LEFT_VAL 12
#define ERR_FUNC_ARGS 13

#define NOT_ARRAY 14
#define NOT_FUNC 15
#define NOT_INT 16
#define NOT_MEMBER 17

#define INCOMPLETE_DEF_FUNC 18



#endif
